package com.example.aphorisms.model

import com.example.aphorisms.R

object AphorismRep {
    val aphList = listOf(
        Aphorism(
            R.drawable.charly_chaplin,
            R.string.Charly_Chaplin_Name,
            R.string.Charly_Chaplin_about,
            R.string.Charly_Chaplin_aff1
        ),
        Aphorism(
            R.drawable.charly_chaplin,
            R.string.Charly_Chaplin_Name,
            R.string.Charly_Chaplin_about,
            R.string.Charly_Chaplin_aff2
        ),
        Aphorism(
            R.drawable.charly_chaplin,
            R.string.Charly_Chaplin_Name,
            R.string.Charly_Chaplin_about,
            R.string.Charly_Chaplin_aff3
        ),
        Aphorism(
            R.drawable.confutsiy,
            R.string.Confutsiy_Name,
            R.string.Confutsiy_about,
            R.string.Confutsiy_aff1
        ),
        Aphorism(
            R.drawable.confutsiy,
            R.string.Confutsiy_Name,
            R.string.Confutsiy_about,
            R.string.Confutsiy_aff2
        ),
        Aphorism(
            R.drawable.confutsiy,
            R.string.Confutsiy_Name,
            R.string.Confutsiy_about,
            R.string.Confutsiy_aff3
        ),
        Aphorism(
            R.drawable.frantsua_laroshfuko,
            R.string.Frantsua_Laroshfuko_Name,
            R.string.Frantsua_Laroshfuko_about,
            R.string.Frantsua_Laroshfuko_aff1
        ),
        Aphorism(
            R.drawable.frantsua_laroshfuko,
            R.string.Frantsua_Laroshfuko_Name,
            R.string.Frantsua_Laroshfuko_about,
            R.string.Frantsua_Laroshfuko_aff2
        ),
        Aphorism(
            R.drawable.frantsua_laroshfuko,
            R.string.Frantsua_Laroshfuko_Name,
            R.string.Frantsua_Laroshfuko_about,
            R.string.Frantsua_Laroshfuko_aff3
        ),
        Aphorism(
            R.drawable.imanuil_kant,
            R.string.Imanuil_Kant_Name,
            R.string.Imanuil_Kant_about,
            R.string.Imanuil_Kant_aff1
        ),
        Aphorism(
            R.drawable.imanuil_kant,
            R.string.Imanuil_Kant_Name,
            R.string.Imanuil_Kant_about,
            R.string.Imanuil_Kant_aff2
        ),
        Aphorism(
            R.drawable.imanuil_kant,
            R.string.Imanuil_Kant_Name,
            R.string.Imanuil_Kant_about,
            R.string.Imanuil_Kant_aff3
        ),
        Aphorism(
            R.drawable.sofi_loren,
            R.string.Sofi_Loren_Name,
            R.string.Sofi_Loren_about,
            R.string.Sofi_Loren_aff1
        ),
        Aphorism(
            R.drawable.sofi_loren,
            R.string.Sofi_Loren_Name,
            R.string.Sofi_Loren_about,
            R.string.Sofi_Loren_aff2
        ),
        Aphorism(
            R.drawable.sofi_loren,
            R.string.Sofi_Loren_Name,
            R.string.Sofi_Loren_about,
            R.string.Sofi_Loren_aff3
        ),
    )
}